query GetMembers(
	$filters: MemberFiltersInput
	$pagination: PaginationArg
	$sort: [String]
) {
	members(filters: $filters, pagination: $pagination, sort: $sort) {
		name
		team {
			name
		}
		pfp {
			url
			alternativeText
		}
		social {
			... on ComponentSharedSocialMedia {
				id
				platform
				url
				icon {
					url
				}
				handle
			}
			... on Error {
				code
				message
			}
		}
	}
}
