query GetSeries(
	$filters: SerieFiltersInput
	$pagination: PaginationArg
	$sort: [String]
) {
	series(filters: $filters, pagination: $pagination, sort: $sort) {
		name
		home_team {
			name
			logo {
				url
				alternativeText
			}
		}
		away_team {
			name
			logo {
				url
				alternativeText
			}
		}
		home_score
		away_score
		date
		game {
			name
		}
	}
}
