query GetTeams(
	$filters: TeamFiltersInput
	$pagination: PaginationArg
	$sort: [String]
) {
	teams(filters: $filters, pagination: $pagination, sort: $sort) {
		name
		game {
			name
		}
		cover_bw{
			url
		}
		cover_rgb{
			url
		}
	}
}
